url: "https://sookyungfarms.github.io"
baseurl: ""

# Site settings
title: 수경팜스
email: sukyeongsmart@gmail.com
description: "수경팜스 홈페이지입니다."


# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : G-KPWFYYL6P9
    anonymize_ip         :


# Team names, titles and social links
people:
- name: 성경천
  pic: 1
  position: 대표
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: 허진노
  pic: 2
  position: 부장
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: 정민재
  pic: 3
  position: 차장
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: 
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: 
  #- title: bitbucket 
  #  url: 
  - title: github
    url: https://github.com/sookyungfarms

# Postal address (add as many lines as necessary)
address:
  - line: 경충대로3054번길 40, 좌측 사무실
  - line: 경기도 이천시

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
